### ISSUE TITLE
Linux SDK, 动态库加载失败

### ISSUE THREAD

**Issue by lujing-jlu** [laugh12321/HCNetSDK-python#2]
```
动态库加载失败
loop[2] find 2 mac and 0 ip
[2023-12-14 18:47:49.956][INF] The COM:HCCoreBase ver is 6.1.4.15, 2020_03_05. Async:1.
[2023-12-14 18:47:49.956][INF] The COM:Core ver is 6.1.9.48, 2023_04_10. Async:1.
[2023-12-14 18:47:49.956][INF] This HCNetSDK ver is 6.1.9.48 Ver 2023_04_10.
[2023-12-14 18:47:49.956][INF] Login dev 172.16.115.202:8000.
[2023-12-14 18:47:49.956][INF] dwTotalNum[2048]
[2023-12-14 18:47:49.956][INF] Private connect 172.16.115.202:8000 sock=142 this=0x140fe514 cmd=0x10000 port=55798
[2023-12-14 18:47:49.956][INF] LogonDev1 in[172.16.115.202:8000]
[2023-12-14 18:47:49.957][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/root/miniconda3/envs/torch180/lib/python3.8/site-packages/HCNetSDK/Libs/linux/libcrypto.so.1.1], hHandleRet[336626704]
[2023-12-14 18:47:49.958][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/root/miniconda3/envs/torch180/lib/python3.8/site-packages/HCNetSDK/Libs/linux/libssl.so.1.1], hHandleRet[336628864]
[2023-12-14 18:47:49.958][INF] SSLTRANSAPI::LoadAPI, libeay, Load Real Path[/root/miniconda3/envs/torch180/lib/python3.8/site-packages/HCNetSDK/Libs/linux/libcrypto.so.1.1]
[2023-12-14 18:47:49.958][INF] SSLTRANSAPI::IsAllAPILoaded, SSL_library_init Unload
[2023-12-14 18:47:49.958][INF] OpenSSL, Not All Function Loaded!
[2023-12-14 18:47:49.958][INF] SSLTRANSAPI::PrintVersion, OpenSSL version info [OpenSSL 1.1.1l  24 Aug 2021]
[2023-12-14 18:47:49.958][INF] CSSLTrans::SSLCtxInit, dwSSLVersion[6], m_fnTLSServerMethod
[2023-12-14 18:47:49.961][ERR] CSSLTrans::SSLTrans_CTX_Load_CA, invalid path[/root/miniconda3/envs/torch180/lib/python3.8/site-packages/HCNetSDK/Libs/linux/cert/\]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch180/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "HikRead.py", line 30, in run
    and client.play()
  File "/backup/projects/onceorauto/camera/PyHikvision/hikvision.py", line 102, in play
    sucess, self.Port = self.sdk.GetPort()
  File "/root/miniconda3/envs/torch180/lib/python3.8/site-packages/HCNetSDK/HCNetSDK.py", line 224, in GetPort
    result = cls.play_sdk.PlayM4_GetPort(byref(port))
AttributeError: type object 'NetClient' has no attribute 'play_sdk'
```

**Comment by laugh12321** [comment]
修改 `~/.bashrc` 文件，在最后一行添加
```
export LD_LIBRARY_PATH = {动态库的绝对路径}:$LD_LIBRARY_PATH
## export LD_LIBRARY_PATH = /root/miniconda3/envs/torch180/lib/python3.8/site-packages/HCNetSDK/Libs/linux:$LD_LIBRARY_PATH
```
保存后，使用命令 `source ~/.bashrc` 使其生效即可。

> [cannot open shared object file: No such file or directory 加载库失败的原因及解决](https://blog.csdn.net/holidayi/article/details/110652213)

**Comment by lujing-jlu** [comment]
谢谢
