### ISSUE TITLE
我是用了example中的preview_video_stream.py，也pip了HCNetSDK-python，但是无法运行这个程序

### ISSUE THREAD

**Issue by xinoer** [laugh12321/HCNetSDK-python#5]
报错如下：
Traceback (most recent call last):
  File "/home/linux/Desktop/pycharm-professional-2022.3.3/pycharm-2022.3.3/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/linux/Desktop/pycharm-professional-2022.3.3/pycharm-2022.3.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/linux/Desktop/pycharm-professional-2022.3.3/pycharm-2022.3.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/linux/PycharmProjects/face_recognition_from_hk/preview_video_stream.py", line 33, in <module>
    from HCNetSDK import *
  File "/home/linux/Desktop/pycharm-professional-2022.3.3/pycharm-2022.3.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
![image](https://github.com/laugh12321/HCNetSDK-python/assets/20312330/e40c822f-8e7a-4754-998f-137542fe59c5)

**Comment by laugh12321** [comment]
请给出完整的报错，从你给的报错来看，问题最终指向`pydev_import_hook.py`这个文件不在`HCNetSDK-python`项目中

**Comment by xinoer** [comment]
以上就是完整的报错

**Comment by xinoer** [comment]
以下是完整报错：
Traceback (most recent call last):
  File "/home/linux/Desktop/pycharm-professional-2022.3.3/pycharm-2022.3.3/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/linux/Desktop/pycharm-professional-2022.3.3/pycharm-2022.3.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/linux/Desktop/pycharm-professional-2022.3.3/pycharm-2022.3.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/linux/PycharmProjects/face_recognition_from_hk/preview_video_stream.py", line 33, in <module>
    from HCNetSDK import *
  File "/home/linux/Desktop/pycharm-professional-2022.3.3/pycharm-2022.3.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/linux/PycharmProjects/face_recognition_from_hk/HCNetSDK.py", line 45, in <module>
    class NetClient(metaclass=Singleton):
  File "/home/linux/PycharmProjects/face_recognition_from_hk/HCNetSDK.py", line 378, in NetClient
    def GetDVRConfig_NFS(cls, lUserId: c_long) -> list[dict[str, str]]:
TypeError: 'type' object is not subscriptable

**Comment by laugh12321** [comment]
你的Python版本是不是低于3.9，这可能是由于`Python 3.9`的类型提示造成的。

**Comment by xinoer** [comment]
是的，我的python是3.8，需要换到3.9吗？

**Comment by laugh12321** [comment]
你创建一个虚拟环境，在Python3.9上试一下吧。
