### ISSUE TITLE
Linux 环境 docker 镜像打包项目时，如何正确设置 LD_LIBRARY_PATH？

### ISSUE THREAD

**Issue by homurax** [laugh12321/HCNetSDK-python#7]
一个 fastapi 项目，其中涉及调用海康SDK抓图，Windows 环境测试没有问题，Linux 环境启动容器时报错。
进入容器内 `echo $LD_LIBRARY_PATH` 也可以输出配置路径。
参考了前面的几个 issues，不知道我这里是否还是 LD_LIBRARY_PATH 设置的问题？

Python：3.8.10

异常信息：
```
2024-10-10 05:28:03,943 - DEBUG - [inference] - inference.py::<module>[line:27]  : SDK_Struct.lib_path_dict = {'windows': '/usr/local/lib/python3.8/dist-packages/HCNetSDK\\Libs\\windows\\', 'linux': '/usr/local/lib/python3.8/dist-packages/HCNetSDK/Libs/linux/'}
2024-10-10 05:28:03,944 - DEBUG - [inference] - inference.py::<module>[line:28]  : LD_LIBRARY_PATH = /usr/local/lib/python3.8/dist-packages/HCNetSDK/Libs/linux
2024-10-10 05:28:03,944 - DEBUG - [inference] - inference.py::<module>[line:29]  : sys_platform = linux
2024-10-10 05:28:03,944 - DEBUG - [inference] - inference.py::<module>[line:30]  : site.getsitepackages() = ['/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.8/dist-packages']
2024-10-10 05:28:04,002 - ERROR - [inference] - inference.py::<module>[line:39]  : type object 'NetClient' has no attribute 'coding_format'
Traceback (most recent call last):
  File "/root/code/app/routers/inference.py", line 33, in <module>
    sdk = NetClient()
  File "/usr/local/lib/python3.8/dist-packages/HCNetSDK/HCNetSDK.py", line 40, in __call__
    self.__instance = super(Singleton, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/HCNetSDK/HCNetSDK.py", line 52, in __init__
    self.SetSDKInitCfg()
  File "/usr/local/lib/python3.8/dist-packages/HCNetSDK/HCNetSDK.py", line 70, in SetSDKInitCfg
    sdk_ComPath.sPath = lib_path_dict[sys_platform].encode(cls.coding_format)
AttributeError: type object 'NetClient' has no attribute 'coding_format'
```

对应代码：
```python
logging.debug(f'SDK_Struct.lib_path_dict = {SDK_Struct.lib_path_dict}')
logging.debug(f'LD_LIBRARY_PATH = {os.environ.get("LD_LIBRARY_PATH")}')
logging.debug(f'sys_platform = {platform.system().lower().strip()}')
logging.debug(f'site.getsitepackages() = {site.getsitepackages()}')

try:
    sdk = NetClient()
    sdk.Init()
    sdk.SetConnectTime(2000, 3)
    sdk.SetReconnect(10000, True)
    sdk.SetLogToFile(3)
except Exception as e:
    logging.error(e, exc_info=True, stack_info=True)
    # os.kill(os.getpid(), signal.SIGINT)
```

dockerfile：
```
FROM ubuntu:20.04

WORKDIR /root/code

RUN apt-get update --fix-missing && apt-get install -y \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /root/code/requirements.txt

RUN pip3 install --break-system-packages --no-cache-dir --upgrade -r /root/code/requirements.txt

COPY ./app /root/code/app

COPY ./log.yaml /root/code/log.yaml

RUN mkdir -p /root/code/logs

ENV LD_LIBRARY_PATH="/usr/local/lib/python3.8/dist-packages/HCNetSDK/Libs/linux:$LD_LIBRARY_PATH"

EXPOSE 8180

ENTRYPOINT ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8180", "--log-config", "log.yaml", "--log-level", "debug"]
```

**Comment by laugh12321** [comment]
@homurax 已经很久没有做海康SDK相关了，暂时给予不了什么帮助。可能是SDK版本太新导致的，可以尝试Release提供的构建好的版本有没有这个问题。

一般情况下，在linux上只需要在启动前设置，LD_LIBRARY_PATH环境变量即可。
